services:
  postgres:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=physics_platform
    ports:
      - "5432:5432"
    volumes:
      - physics_data:/var/lib/postgresql/data
      - ./install/db-schema.sql:/docker-entrypoint-initdb.d/create_tables.sql

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    volumes:
      - ./install/pgadmin-servers.json:/pgadmin4/servers.json
      - ./install/pgadmin-pgpass.txt:/pgpass

volumes:
  physics_data:
